version: '2'

services:
  jenkins:
    image: 'jenkins/jenkins:2.174-alpine'
    ports:
      - '80:8080'
      - '50000:50000'
    environment:
      JENKINS_HOME: '/jenkins_data'
    volumes:
      - './jenkins_data:/jenkins_data'
    restart: 'always'
    stdin_open: true
    tty: true
